### ISSUE TITLE
Apply Vagrant Provisioning

### ISSUE THREAD

**Issue by cdaf** [Semprini/cbe#2]
To support automated nightly regression, Vagrant automation needs to be applied.

**Comment by cdaf** [comment]
I appear to be unable to assign this to myself?

**Comment by cdaf** [comment]
When you merge a fork, will it collapse my existing one and allow me to create another, or is the fork persistent?

**Comment by Semprini** [comment]
Your fork is persistent until you close it. You can refresh your fork from it's parent:https://gist.github.com/CristinaSolana/1885435

**Comment by cdaf** [comment]
oh, client side command line, how quaint.
